"""
Master orchestrator for ICEBREAKER Certs & Grading ingest.
Runs all 6 individual scripts, logs results, sends Outlook email.
Called by Automator/run.bat on schedule.
"""
import datetime
import sys
import traceback
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────────
CODE_DIR = Path(__file__).resolve().parent
REPO_DIR = CODE_DIR.parent
LOG_FILE = REPO_DIR / "Automator" / "run_log.txt"
LOG_FILE.parent.mkdir(exist_ok=True)

sys.path.insert(0, str(CODE_DIR))

# ── Logging ────────────────────────────────────────────────────────────────────
_log_lines = []

def log(msg: str):
    ts = datetime.datetime.now().strftime("%H:%M:%S")
    line = f"[{ts}] {msg}"
    print(line)
    _log_lines.append(line)


def append_to_logfile(run_date: str, results: list):
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(f"\n{'='*60}\n")
        f.write(f"Run: {run_date}\n")
        f.write(f"{'='*60}\n")
        for line in _log_lines:
            f.write(line + "\n")


# ── Email via Outlook ──────────────────────────────────────────────────────────
def send_email(subject: str, body_html: str):
    try:
        import win32com.client
        outlook = win32com.client.Dispatch("Outlook.Application")
        mail = outlook.CreateItem(0)
        mail.To = "virat.arya@etgworld.com"
        mail.Subject = subject
        mail.HTMLBody = body_html
        mail.Send()
        log("Email sent.")
    except Exception as exc:
        log(f"Email failed (Outlook may be closed): {exc}")


def build_html_email(run_date: str, results: list, log_lines: list) -> str:
    rows_html = ""
    for r in results:
        status_color = "#1b5e20" if r["status"] == "OK" else "#b71c1c"
        status_bg = "#e8f5e9" if r["status"] == "OK" else "#ffebee"
        rows_html += f"""
        <tr>
            <td style="padding:6px 12px;border-bottom:1px solid #eee;font-weight:600">{r['script']}</td>
            <td style="padding:6px 12px;border-bottom:1px solid #eee;text-align:center;
                       background:{status_bg};color:{status_color};font-weight:700">{r['status']}</td>
            <td style="padding:6px 12px;border-bottom:1px solid #eee;text-align:right">{r.get('rows','—')}</td>
            <td style="padding:6px 12px;border-bottom:1px solid #eee">{r.get('date_range','—')}</td>
            <td style="padding:6px 12px;border-bottom:1px solid #eee;color:#888;font-size:0.85em">{r.get('error','')}</td>
        </tr>"""

    all_ok = all(r["status"] == "OK" for r in results)
    summary_color = "#1b5e20" if all_ok else "#b71c1c"
    summary_text = "All scripts completed successfully." if all_ok else "One or more scripts FAILED — check log."

    log_html = "\n".join(line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;") for line in log_lines)

    return f"""
    <html><body style="font-family:Arial,sans-serif;font-size:13px;color:#222">
    <h2 style="color:#1f2a44;margin-bottom:4px">ICEBREAKER Certs & Grading — Daily Ingest</h2>
    <p style="color:#888;margin-top:0">{run_date}</p>
    <p style="color:{summary_color};font-weight:700">{summary_text}</p>
    <table style="border-collapse:collapse;width:100%;max-width:780px;margin-top:12px">
        <thead>
            <tr style="background:#1f2a44;color:white">
                <th style="padding:8px 12px;text-align:left">Script</th>
                <th style="padding:8px 12px">Status</th>
                <th style="padding:8px 12px;text-align:right">Rows</th>
                <th style="padding:8px 12px;text-align:left">Date Range</th>
                <th style="padding:8px 12px;text-align:left">Error</th>
            </tr>
        </thead>
        <tbody>{rows_html}</tbody>
    </table>
    <h3 style="color:#1f2a44;margin-top:28px;margin-bottom:6px">Full Log</h3>
    <pre style="background:#f5f5f5;border:1px solid #ddd;padding:12px;font-size:11px;
                line-height:1.5;overflow-x:auto;white-space:pre-wrap;word-wrap:break-word;
                max-height:600px;overflow-y:auto">{log_html}</pre>
    <p style="margin-top:20px;color:#aaa;font-size:0.8em">
        ICEBREAKER • Certs & Grading • Auto-generated by Master_Ingest.py
    </p>
    </body></html>"""


# ── Run one script ─────────────────────────────────────────────────────────────
def run_script(module_name: str, func_name: str, label: str) -> dict:
    log(f"--- {label} ---")
    result = {"script": label, "status": "FAIL", "rows": None, "date_range": None, "error": ""}
    try:
        import importlib
        mod = importlib.import_module(module_name)
        importlib.reload(mod)
        df = getattr(mod, func_name)()
        if df is not None and hasattr(df, "__len__"):
            result["rows"] = f"{len(df):,}"
            if "Date" in df.columns:
                result["date_range"] = f"{df['Date'].min().date()} → {df['Date'].max().date()}"
            elif "PanelDate" in df.columns:
                result["date_range"] = f"{df['PanelDate'].min().date()} → {df['PanelDate'].max().date()}"
            elif "PublishedDate" in df.columns:
                result["date_range"] = f"{df['PublishedDate'].min().date()} → {df['PublishedDate'].max().date()}"
        result["status"] = "OK"
        log(f"    OK — {result['rows']} rows | {result['date_range']}")
    except Exception:
        err = traceback.format_exc()
        result["error"] = err.splitlines()[-1][:120]
        log(f"    FAILED: {result['error']}")
        for line in err.splitlines():
            log(f"      {line}")
    return result


# ── Main ───────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    run_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    log(f"ICEBREAKER Certs & Grading — Master Ingest started: {run_date}")
    log(f"Repo: {REPO_DIR}")

    SCRIPTS = [
        ("RC_Ingest",          "build_rc",          "LRC Certs (Robusta)"),
        ("KC_Ingest",          "build_kc",          "KC Certs (Arabica)"),
        ("CC_Ingest",          "build_cc",          "CC Certs (Cocoa US)"),
        ("LCC_Ingest",         "build_lcc",         "LCC Certs (Cocoa UK)"),
        ("RC_Grading_Ingest",  "build_rc_grading",  "RC Grading (Robusta)"),
        ("LCC_Grading_Ingest", "build_lcc_grading", "LCC Grading (Cocoa UK)"),
    ]

    results = []
    for module, func, label in SCRIPTS:
        results.append(run_script(module, func, label))

    ok_count = sum(1 for r in results if r["status"] == "OK")
    fail_count = len(results) - ok_count
    log(f"Ingest complete: {ok_count} OK / {fail_count} FAILED")

    append_to_logfile(run_date, results)

    subject = f"[{'OK' if fail_count == 0 else 'FAIL'}] ICEBREAKER Certs & Grading — {run_date}"
    send_email(subject, build_html_email(run_date, results, _log_lines))

    # Exit with non-zero code if any script failed (so bat can detect failure)
    sys.exit(0 if fail_count == 0 else 1)
